name: Node.js Package

on:
  push:
    branches:
      - development

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@gtamasmolnar'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.READ_PACKAGE_ACTION_TOKEN}}
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.CREATE_PACKAGE_ACTION_TOKEN}}
